os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install xclip; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo easy_install pip; fi
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls
